//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChairtyApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public Nullable<float> Magnitude { get; set; }
        public Nullable<float> Landitude { get; set; }
        public string CreditNumber { get; set; }
        public int CreditId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public string IdentificationNumber { get; set; }
        public string BloodCategory { get; set; }
    
        public virtual Credit Credit { get; set; }
        public virtual UserRule UserRule { get; set; }
    }
}
