//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChairtyApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Donations = new HashSet<Donation>();
            this.Requists = new HashSet<Requist>();
        }
    
        public int Id { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public Nullable<float> Magnitude { get; set; }
        public Nullable<float> Landitude { get; set; }
        public string CreditNumber { get; set; }
        public int CreditId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public string IdentificationNumber { get; set; }
        public string BloodCategory { get; set; }
    
        public virtual Credit Credit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requist> Requists { get; set; }
        public virtual UserRule UserRule { get; set; }
    }
}
