//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChairtyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class donationTbl
    {
        public int donationId { get; set; }
        public bool isCredit { get; set; }
        public int costOfDonation { get; set; }
        public int userId { get; set; }
    
        public virtual userTbl userTbl { get; set; }
    }
}
