//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChairtyApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTbl()
        {
            this.donationTbls = new HashSet<donationTbl>();
            this.requestTbls = new HashSet<requestTbl>();
        }
    
        public int userId { get; set; }
        public string userName { get; set; }
        public string phoneNum { get; set; }
        public float Magnitude { get; set; }
        public float Landitude { get; set; }
        public string creditNum { get; set; }
        public string creditType { get; set; }
        public int ruleId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donationTbl> donationTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requestTbl> requestTbls { get; set; }
        public virtual ruleTbl ruleTbl { get; set; }
    }
}
